name: TEST-AND-QUALITY-CHECK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash
    working-directory: . # Adjust this if you change your project structure

env:
  UV_DEFAULT_INDEX: https://artifactory.dbgcloud.io/artifactory/api/pypi/cio-ecc-itsdesign-pypi-dev/simple

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ecceps-docker-test-local.artifactory.dbgcloud.io/rhel8-ubi/rhel8-ubi-python:3.11.9-4
      options: --user root
      credentials:
        username: ${{ secrets.ARTIFACTORY_API_USER }}
        password: ${{ secrets.ARTIFACTORY_API_TOKEN }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install uv
        run: python -m pip install uv --index-url=$UV_DEFAULT_INDEX

      - name: Install Dependencies
        run: uv pip install --system -e .[dev] --index-url=$UV_DEFAULT_INDEX

      - name: run black
        run: tox -e black

      - name: run flake8
        run: tox -e flake8

      - name: run isort
        run: tox -e isort

      - name: run the pipline
        run: |
          build
          sphinx-build -E -d .doctree -c . rst_source docs
          
      - name: Upload the page to artifact
        uses: EXG-dev-confidential/exg.upload-pages-artifact@v2/exg-fix
        with:
          path: docs/

  # Deployment job
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2