name: TEST-AND-QUALITY-CHECK

on:
  push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master

defaults:
  run:
    shell: bash
    working-directory: . # Adjust this if you change your project structure

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v5
      
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v6
        # with:
        #   # Semantic version range syntax or exact version of a Python version
        #   python-version: '3.12'
      
      - name: create virtual environment
        run: python3 -m venv venv
             source venv/bin/activate
             python3 -m pip install --upgrade pip
             pip install ".[dev, tox]"
      
      # - name: Activabte virtusal environment
      
      # - name: Upgrade pip

      # - name: Install Dependencies

      - name: run black
        run: tox -e black

      - name: run flake8
        run: tox -e flake8

      - name: run isort
        run: tox -e isort

      - name: run the pipline
        run: |
          build
          sphinx-build -E -d .doctree -c . rst_source docs
          
      - name: Upload the page to artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # Deployment job
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4